Lab2_2/Models/CalculationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab2_2.Models
{
    public class CalculationModel
    {
        public int Val1 { get; set; }
        public int Val2 { get; set; }
        public string Operation { get; set; }
        public string Result { get; set; }

        public void calc_Result()
        {
            Result = "" + Val1;
            switch (Operation)
            {
                case "+":
                    Result += " + " + Val2 + " = " + (Val1 + Val2);
                    break;
                case "-":
                    Result += " - " + Val2 + " = " + (Val1 - Val2);
                    break;
                case "*":
                    Result += " * " + Val2 + " = " + (Val1 * Val2);
                    break;
                case "/":
                    Result += " / " + Val2 + " = ";
                    if (Val2 != 0) Result += (Val1 / Val2);
                    else Result += "ERROR: Division by zero";
                    break;
            }
        }
    }
}

Lab2_2/Models/ErrorViewModel.cs
using System;

namespace Lab2_2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab2_2/Controllers/CalculationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Lab2_2.Models;

namespace Lab2_2.Controllers
{
    public class CalculationController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public CalculationController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult ManualSingle()
        {
            if (Request.Method.Equals("POST", StringComparison.OrdinalIgnoreCase))
            {
                CalculationModel calc = new CalculationModel();
                if (Request.Form["Val1"] == "" && Request.Form["Val2"] == "")
                {
                    calc.Val1 = 0;
                    calc.Val2 = 0;
                }
                else if (Request.Form["Val1"] != "" && Request.Form["Val2"] == "")
                {
                    calc.Val1 = Int32.Parse(Request.Form["Val1"]); 
                    calc.Val2 = 0;
                }
                else if (Request.Form["Val1"] == "" && Request.Form["Val2"] != "")
                {
                    calc.Val1 = 0;
                    calc.Val2 = Int32.Parse(Request.Form["Val2"]);
                }
                else
                {
                    calc.Val1 = Int32.Parse(Request.Form["Val1"]);
                    calc.Val2 = Int32.Parse(Request.Form["Val2"]);
                }

                calc.Operation = Request.Form["Operation"];
                calc.calc_Result();
                ViewBag.Result = calc.Result;
                return View("Result");
            }
            else return View();
        }


        [HttpGet]
        public IActionResult ManualSeparate()
        {
            return View();
        }

        [HttpPost, ActionName("ManualSeparate")]
        public IActionResult ManualSeparatePost()
        {
            CalculationModel calc = new CalculationModel();
            if (Request.Form["Val1"] == "" && Request.Form["Val2"] == "")
            {
                calc.Val1 = 0;
                calc.Val2 = 0;
            }
            else if (Request.Form["Val1"] != "" && Request.Form["Val2"] == "")
            {
                calc.Val1 = Int32.Parse(Request.Form["Val1"]);
                calc.Val2 = 0;
            }
            else if (Request.Form["Val1"] == "" && Request.Form["Val2"] != "")
            {
                calc.Val1 = 0;
                calc.Val2 = Int32.Parse(Request.Form["Val2"]);
            }
            else
            {
                calc.Val1 = Int32.Parse(Request.Form["Val1"]);
                calc.Val2 = Int32.Parse(Request.Form["Val2"]);
            }

            calc.Operation = Request.Form["Operation"];
            calc.calc_Result();
            ViewBag.Result = calc.Result;
            return View("Result");
        }


        [HttpGet]
        public IActionResult ModelParam()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ModelParam(int Val1, int Val2, string Operation)
        {
            CalculationModel calc = new CalculationModel();
            calc.Val1 = Val1;
            calc.Val2 = Val2;
            calc.Operation = Operation;
            calc.calc_Result();
            ViewBag.Result = calc.Result;
            return View("Result");
        }


        [HttpGet]
        public IActionResult ModelSeparate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ModelSeparate(CalculationModel calc)
        {
            calc.calc_Result();
            ViewBag.Result = calc.Result;
            return View("Result");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab2_2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Lab2_2.Models;

namespace Lab2_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab2_2/Views/Calculation/ManualSeparate.cshtml
@{ViewData["Title"] = "ManualWithSeparateHandlers";}

<form method="post">
    <h1>ManualWithSeparateHandlers</h1>
    <input type="number" name="Val1" style="width:300px; height:35px"/><br>
    <select name="Operation">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
    </select><br>
    <input type="number" name="Val2" style="width:300px; height:35px"><br>
    <input type="submit" value="Submit">
</form>

Lab2_2/Views/Calculation/ManualSingle.cshtml
@{ViewData["Title"] = "Manual";}

<form method="post">
    <h1>Manual</h1>
    <input type="number" name="Val1" style="width:300px; height:35px"/><br>
    <select name="Operation">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
    </select><br>
    <input type="number" name="Val2" style="width:300px; height:35px"><br>
    <input type="submit" value="Submit">
</form>

Lab2_2/Views/Calculation/ModelParam.cshtml
@{ViewData["Title"] = "ModelBindingInParameters";}

<form method="post">
    <h1>ModelBindingInParameters</h1>
    <input type="number" name="Val1" style="width:300px; height:35px" /><br>
    <select name="Operation">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
    </select><br>
    <input type="number" name="Val2" style="width:300px; height:35px"><br>
    <input type="submit" value="Submit">
</form>

Lab2_2/Views/Calculation/ModelSeparate.cshtml
@{ ViewData["Title"] = "ModelBindingInSeparateModel"; }

<form method="post">
    <h1>ModelBindingInSeparateModel</h1>
    <input type="number" name="Val1" style="width:300px; height:35px" /><br>
    <select name="Operation">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
    </select><br>
    <input type="number" name="Val2" style="width:300px; height:35px"><br>
    <input type="submit" value="Submit">
</form>

Lab2_2/Views/Calculation/Result.cshtml
@{ViewData["Title"] = "Result";}

<h1>Result</h1>
<p style="font-size:25px">@ViewBag.Result</p>

Lab2_2/Views/Home/Index.cshtml
@{ViewData["Title"] = "Home Page";}

<div>
    <h1>Form parameters parsing demo</h1>

    <ul>
        <li>
            <a asp-area="" asp-controller="Calculation" asp-action="ManualSingle">Manual parsing in single action</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Calculation" asp-action="ManualSeparate">Manual parsing in separate actions</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Calculation" asp-action="ModelParam">Model binding (parameters)</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Calculation" asp-action="ModelSeparate">Model binding (separate model)</a>
        </li>
    </ul>
</div>

Lab2_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend2 </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:black">
            <div class="container">
                <a class="navbar-brand" style="color:grey;" asp-area="" asp-controller="Home" asp-action="Index">Backend2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation" style="background-color: gray; ">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color:grey;" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top" style="width: 85%; max-width: 1140px; margin:auto;">
        <div class="container mt-4">
            &copy; 2021 - Backend2
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>